/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MealPackage } from "./MealPackage";
import { MealPackageCountArgs } from "./MealPackageCountArgs";
import { MealPackageFindManyArgs } from "./MealPackageFindManyArgs";
import { MealPackageFindUniqueArgs } from "./MealPackageFindUniqueArgs";
import { DeleteMealPackageArgs } from "./DeleteMealPackageArgs";
import { MealPackageService } from "../mealPackage.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => MealPackage)
export class MealPackageResolverBase {
  constructor(
    protected readonly service: MealPackageService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "MealPackage",
    action: "read",
    possession: "any",
  })
  async _mealPackagesMeta(
    @graphql.Args() args: MealPackageCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [MealPackage])
  @nestAccessControl.UseRoles({
    resource: "MealPackage",
    action: "read",
    possession: "any",
  })
  async mealPackages(
    @graphql.Args() args: MealPackageFindManyArgs
  ): Promise<MealPackage[]> {
    return this.service.mealPackages(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => MealPackage, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "MealPackage",
    action: "read",
    possession: "own",
  })
  async mealPackage(
    @graphql.Args() args: MealPackageFindUniqueArgs
  ): Promise<MealPackage | null> {
    const result = await this.service.mealPackage(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => MealPackage)
  @nestAccessControl.UseRoles({
    resource: "MealPackage",
    action: "delete",
    possession: "any",
  })
  async deleteMealPackage(
    @graphql.Args() args: DeleteMealPackageArgs
  ): Promise<MealPackage | null> {
    try {
      return await this.service.deleteMealPackage(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
